require("toriui.uielement3d")

---@alias ClanJoinMode
---| 0 CLAN_JOINMODE_INVITEONLY
---| 1 CLAN_JOINMODE_FREEFORALL
CLAN_JOINMODE_INVITEONLY = 0
CLAN_JOINMODE_FREEFORALL = 1

---@alias ClanActivityStatus
---| 0 CLAN_ACTIVITY_DEAD
---| 1 CLAN_ACTIVITY_ALIVE
---| 2 CLAN_ACTIVITY_ACTIVE
CLAN_ACTIVITY_DEAD = 0
CLAN_ACTIVITY_ALIVE = 1
CLAN_ACTIVITY_ACTIVE = 2

---@class Clan
---@field id integer Public clan id in the clans system
---@field name string Clan name
---@field tag string Clan tag
---@field is_official boolean
---@field rank integer
---@field level integer
---@field xp integer
---@field members_total integer
---@field join_mode ClanJoinMode
---@field top_achievement integer Clan's selected achievement id
---@field is_active ClanActivityStatus
---@field members string[] List of all clan members' names
---@field leaders string[] List of all clan leaders' names
---@field memberscustom string Custom display name for clan members
---@field leaderscustom string Custom display name for clan leaders
---@field colorNegative boolean Internal flag to tell if we should use dark font color for clan ui
---@field bgColor Color Custom clan background color
---@field xpBarBgColor Color Custom clan xp bar background color, autogenerated from `bgColor`
---@field xpBarColor Color Custom clan xp bar color, autogenerated from `bgColor`
---@field xpBarAccentTopColor Color Custom clan xp bar accent top color, autogenerated from `bgColor`
---@field xpBarAccentBotColor Color Custom clan xp bar accent bottom color, autogenerated from `bgColor`

---@class ClanLevel
---@field id integer
---@field min_xp integer Clan xp requirement for the level
---@field max_members integer Maximum number of clan members allowed at this level
---@field official_only boolean Whether reaching this level requires the clan to be official

---@class ClanAchievement
---@field id integer
---@field name string Achievement name
---@field description string Achievement description text

if (Clans == nil) then
	---**Toribash clans manager class**
	---
	---**Version 5.60 updates**
	---* Updated internals to match new language design
	---* Added documentation with EmmyLua annotations
	---@class Clans
	---@field Data Clan[] Cached information about all Toribash clans with at least 1 member
	---@field Levels ClanLevel[] Cached information about clan levels
	---@field Achievements ClanAchievement[] Cached information about clan achivemenets
	Clans = {
		Data = {},
		Levels = {},
		Achievements = {},
		UpdateTime = -100,
		DefaultLogo = "../textures/clans/default.tga",
		ver = 5.60
	}
	Clans.__index = Clans
end

---Queues clans data for download.
---
---*This function has spam protection and will return early on frequent calls or if there's already at least one clan datafile in the queue.*
---@return boolean
function Clans:download()
	local clock = os.clock_real()

	if (clock - Clans.UpdateTime < 10) then
		return false
	end
	for _, v in pairs(get_downloads()) do
		if (v:find("clans/clan%w+%.txt$")) then
			return false
		end
	end

	Clans.UpdateTime = clock
	download_clan()

	return true
end

---Populates clan data and caches it in Clans object
---@param override ?boolean Whether to reset existing clan data cache
---@return integer|nil #Number of clans in the cache
function Clans:getClanData(override)
	if (override) then
		Clans.Data = {}
	end
	local numClans = table.size(Clans.Data)
	if (numClans > 0) then
		return numClans
	end

	local data_types = {
		{ "id", numeric = true },
		{ "name" },
		{ "tag" },
		{ "is_official", boolean = true },
		{ "rank", numeric = true },
		{ "level", numeric = true },
		{ "xp", numeric = true },
		{ "members_total", numeric = true },
		{ "join_mode", numeric = true },
		{ "top_achievement", numeric = true },
		{ "is_active", numeric = true },
		{ "members" },
		{ "leaders" },
		{ "bgColor" },
		{ "leaderscustom" },
		{ "memberscustom" }
	}
	local file = Files:open("clans/clans.txt")
	if (not file.data) then
		return nil
	end

	local fileData = file:readAll()
	file:close()

	for _, ln in pairs(fileData) do
		if string.match(ln, "^CLAN") then
			local _, segments = ln:gsub("\t", "")
			local data_stream = { ln:match(("([^\t]*)\t"):rep(segments)) }

			local clanInfo = {}
			for i, v in pairs(data_types) do
				clanInfo[v[1]] = data_stream[i + 1]
				if (v.numeric) then
					clanInfo[v[1]] = tonumber(clanInfo[v[1]])
				end
				if (v.boolean) then
					clanInfo[v[1]] = clanInfo[v[1]] == "1"
				end
			end

			local membersList = clanInfo.members
			local leadersList = clanInfo.leaders
			clanInfo.members, clanInfo.leaders = {}, {}
			for player in membersList:gmatch("%S+") do
				table.insert(clanInfo.members, player)
			end
			for player in leadersList:gmatch("%S+") do
				---Insert leaders both to leaders list AND members list
				table.insert(clanInfo.members, player)
				table.insert(clanInfo.leaders, player)
			end
			---@diagnostic disable-next-line: param-type-mismatch
			if (string.len(clanInfo.bgColor) > 0) then
				---@diagnostic disable-next-line: param-type-mismatch
				clanInfo.bgColor = get_color_from_hex(clanInfo.bgColor)
				clanInfo.xpBarBgColor = table.clone(clanInfo.bgColor)
				clanInfo.xpBarColor = table.clone(clanInfo.bgColor)
				clanInfo.xpBarAccentTopColor = table.clone(clanInfo.bgColor)
				clanInfo.xpBarAccentBotColor = table.clone(clanInfo.bgColor)

				for i = 1, 3 do
					clanInfo.xpBarBgColor[i] = clanInfo.xpBarBgColor[i] + 0.05
					clanInfo.xpBarColor[i] = clanInfo.xpBarColor[i] - 0.1
					clanInfo.xpBarAccentTopColor[i] = clanInfo.xpBarAccentTopColor[i] + 0.1
					clanInfo.xpBarAccentBotColor[i] = clanInfo.xpBarAccentBotColor[i] - 0.2
				end
				if (get_color_contrast_ratio(clanInfo.bgColor) > 0.66) then
					clanInfo.colorNegative = true
				end
			else
				clanInfo.bgColor = nil
			end

			Clans.Data[clanInfo.id] = clanInfo
			numClans = numClans + 1
		end
	end
	return numClans
end

---Populates clan levels data and caches it in Clans object
---@param override ?boolean Whether to reset existing clan levels data cache
---@return integer|nil #Number of clan levels in the cache
function Clans:getLevelData(override)
	if (override) then
		Clans.levels = {}
	end
	local numLevels = #Clans.Levels
	if (numLevels > 0) then
		return numLevels
	end

	local data_types = {
		{ "id", numeric = true },
		{ "min_xp", numeric = true },
		{ "max_members", numeric = true },
		{ "official_only", boolean = true }
	}

	local file = Files:open("clans/clanlevels.txt")
	if (not file.data) then
		return nil
	end

	local fileData = file:readAll()
	file:close()

	for _, ln in pairs(fileData) do
		if string.match(ln, "^LEVEL") then
			local _, segments = ln:gsub("\t", "")
			local data_stream = { ln:match(("([^\t]*)\t"):rep(segments)) }

			local levelInfo = {}
			for i,v in pairs(data_types) do
				levelInfo[v[1]] = data_stream[i + 1]
				if (v.numeric) then
					levelInfo[v[1]] = tonumber(levelInfo[v[1]])
				end
				if (v.boolean) then
					levelInfo[v[1]] = levelInfo[v[1]] == "1"
				end
			end

			Clans.Levels[levelInfo.id] = levelInfo
			numLevels = numLevels + 1
		end
	end
	return numLevels
end

---Populates clan achievements data and caches it in Clans object
---@param override ?boolean Whether to reset existing clan achievements data cache
---@return integer|nil #Number of clan achievements in the cache
function Clans:getAchievementData(override)
	if (override) then
		Clans.Achievements = {}
	end
	local numAchievements = #Clans.Achievements
	if (numAchievements > 0) then
		return numAchievements
	end

	local data_types = {
		{ "id", numeric = true },
		{ "name" },
		{ "description" }
	}
	local file = Files:open("clans/clanachievements.txt")
	if (not file.data) then
		return nil
	end
	local fileData = file:readAll()
	file:close()

	for _, ln in pairs(fileData) do
		if string.match(ln, "^ACHIEVEMENT") then
			local segments = 4
			local data_stream = { ln:match(("([^\t]*)\t"):rep(segments)) }

			local achievementInfo = {}
			for i,v in pairs(data_types) do
				achievementInfo[v[1]] = data_stream[i + 1]
				if (v.numeric) then
					achievementInfo[v[1]] = tonumber(achievementInfo[v[1]])
				end
				if (v.boolean) then
					achievementInfo[v[1]] = achievementInfo[v[1]] == "1"
				end
			end

			Clans.Achievements[achievementInfo.id] = achievementInfo
			numAchievements = numAchievements + 1
		end
	end
	return numAchievements
end

---Exits clans menu and returns to last displayed main menu screen
function Clans:quit()
	TBMenu.CurrentSection:kill(true)
	TBMenu:showNavigationBar()
	TBMenu:openMenu(TB_LAST_MENU_SCREEN_OPEN)
end

function Clans:getNavigationButtons(showBack)
	if (get_option("newmenu") == 1) then
		return {
			{
				text = TB_MENU_LOCALIZED.NAVBUTTONBACK,
				action = function()
					TB_LAST_MENU_SCREEN_OPEN = 9
					TB_MENU_SPECIAL_SCREEN_ISOPEN = 0
					TBMenu:clearNavSection()
					TBMenu:showNavigationBar()
					TBMenu:showClans()
				end,
			}
		}
	end

	local buttonText = get_option("newmenu") == 0 and TB_MENU_LOCALIZED.NAVBUTTONEXIT or TB_MENU_LOCALIZED.NAVBUTTONTOMAIN
	local buttonsData = {
		{
			text = buttonText,
			action = function() TB_MENU_CLANS_OPENCLANID = 0 Clans:quit() end,
			width = get_string_length(buttonText, FONTS.BIG) * 0.65 + 30
		}
	}
	if (showBack) then
		local backButton = {
			text = TB_MENU_LOCALIZED.NAVBUTTONBACK,
			action = function() TB_MENU_CLANS_OPENCLANID = 0 Clans:showMain(TBMenu.CurrentSection) end,
			width = get_string_length(TB_MENU_LOCALIZED.NAVBUTTONBACK, FONTS.BIG) * 0.65 + 30
		}
		table.insert(buttonsData, backButton)
	end
	return buttonsData
end

function Clans:isBeginnerClan(clanid)
	if (clanid == 2193 or clanid == 2194) then
		return true
	end
	return false
end

function Clans:showMain(viewElement, clantag)
	if (not Clans:getLevelData() or not Clans:getAchievementData() or not Clans:getClanData()) then
		Clans:download()
		local loader = UIElement:new({
			parent = viewElement,
			pos = { 5, 0 },
			size = { viewElement.size.w - 10, viewElement.size.h },
			bgColor = TB_MENU_DEFAULT_BG_COLOR
		})
		loader:addCustomDisplay(false, function()
				if (#get_downloads() == 0) then
					loader:kill()
					Clans:showMain(viewElement, clantag)
				end
			end)
		local loadingText = UIElement:new({
			parent = loader,
			pos = { loader.size.w / 4, loader.size.h / 3 },
			size = { loader.size.w / 2, loader.size.h / 3 }
		})
		TBMenu:displayLoadingMark(loadingText, TB_MENU_LOCALIZED.CLANSUPDATINGWAIT)
	end

	if (clantag) then
		local clanid
		for i,v in pairs(Clans.Data) do
			if (v.tag == clantag) then
				clanid = v.id
				break
			end
		end
		Clans:showClan(viewElement, clanid)
		return
	end
	viewElement:kill(true)
	local clanListSettings = UIElement:new({
		parent = viewElement,
		pos = { 5, 0 },
		size = { viewElement.size.w * 0.3 - 10, viewElement.size.h },
		bgColor = TB_MENU_DEFAULT_BG_COLOR
	})
	Clans:showUserClan(clanListSettings)
	local clanView = UIElement:new({
		parent = viewElement,
		pos = { viewElement.size.w * 0.3 + 5, 0 },
		size = { viewElement.size.w * 0.7 - 10, viewElement.size.h },
		bgColor = TB_MENU_DEFAULT_BG_COLOR
	})
	Clans:showClanList(clanView)
end

function Clans:showUserClan(viewElement)
	local clanUserBotSmudge = TBMenu:addBottomBloodSmudge(viewElement, 1)
	local clanid = TB_MENU_PLAYER_INFO.clan.id
	if (clanid ~= 0) then
		local userClanTitle = UIElement:new({
			parent = viewElement,
			pos = { 0, 0 },
			size = { viewElement.size.w, viewElement.size.h / 8 }
		})
		userClanTitle:addCustomDisplay(true, function()
				userClanTitle:uiText(TB_MENU_LOCALIZED.CLANSMYCLAN, nil, nil, FONTS.BIG, nil, 0.7, nil, nil, nil, nil, 0.2)
			end)
		local buttonHeight = viewElement.size.h / 6
		local clanView = UIElement:new({
			parent = viewElement,
			pos = { 0, viewElement.size.h / 7 },
			size = { viewElement.size.w, viewElement.size.h / 3 * 2 }
		})
		local heightMod = 0
		if (clanView.size.h / 3 * 2 > 60) then
			local iconSize = clanView.size.h / 3 * 2 > 256 and 256 or math.floor(clanView.size.h / 3 * 2)
			local clanLogo = UIElement:new({
				parent = clanView,
				pos = { (clanView.size.w - iconSize) / 2, 0 },
				size = { iconSize, iconSize },
				bgImage =  { "../textures/clans/"..clanid..".tga", Clans.DefaultLogo }
			})
			heightMod = iconSize
			Clans:loadClanLogo(clanid, clanLogo)
		end
		local clanInfo = UIElement:new({
			parent = clanView,
			pos = { clanView.size.w / 10, clanView.size.h / 3 * 2 },
			size = { clanView.size.w / 10 * 8, clanView.size.h / 3 }
		})
		local clanName = UIElement:new({
			parent = clanInfo,
			pos = { 0, 0 },
			size = { clanInfo.size.w, clanInfo.size.h / 2 }
		})
		local clanNameSize = 0.8
		while (not clanName:uiText(TB_MENU_PLAYER_INFO.clan.name, nil, nil, FONTS.BIG, LEFT, clanNameSize, nil, nil, nil, nil, nil, true)) do
			clanNameSize = clanNameSize - 0.05
		end
		clanName:addCustomDisplay(true, function()
				clanName:uiText(TB_MENU_PLAYER_INFO.clan.name, nil, nil, FONTS.BIG, nil, clanNameSize)
			end)
		local memberStatus = UIElement:new({
			parent = clanInfo,
			pos = { 0, clanInfo.size.h / 2 },
			size = { clanInfo.size.w, clanInfo.size.h / 4 },
		})
		if (TB_MENU_PLAYER_INFO.clan.isleader) then
			local memberStatusSize = 1
			while (not memberStatus:uiText(TB_MENU_LOCALIZED.CLANSCLANLEADER, nil, nil, 4, LEFT, memberStatusSize, nil, nil, nil, nil, nil, true)) do
				memberStatusSize = memberStatusSize - 0.05
			end
			memberStatus:addCustomDisplay(true, function()
					memberStatus:uiText(TB_MENU_LOCALIZED.CLANSCLANLEADER, nil, nil, 4, CENTERMID, memberStatusSize)
				end)
			local otherMembers = UIElement:new({
				parent = clanInfo,
				pos = { 0, clanInfo.size.h / 4 * 3 },
				size = { clanInfo.size.w, clanInfo.size.h / 4 }
			})
			if (Clans.Data[clanid] and #Clans.Data[clanid].leaders > 1) then
				local leader1 = math.random(1, #Clans.Data[clanid].leaders)
				while (Clans.Data[clanid].leaders[leader1]:lower() == TB_MENU_PLAYER_INFO.username:lower()) do
					leader1 = math.random(1, #Clans.Data[clanid].leaders)
				end
				local otherMembersStr = TB_MENU_LOCALIZED.CLANSTOGETHERWITH .. " " .. Clans.Data[clanid].leaders[leader1]
				if (#Clans.Data[clanid].leaders > 2) then
					local leader2 = math.random(1, #Clans.Data[clanid].leaders)
					while (Clans.Data[clanid].leaders[leader2]:lower() == TB_MENU_PLAYER_INFO.username:lower() or leader2 == leader1) do
						leader2 = math.random(1, #Clans.Data[clanid].leaders)
					end
					if (otherMembers:uiText(otherMembersStr .. " " .. TB_MENU_LOCALIZED.GENERALSTRINGAND .. " " .. Clans.Data[clanid].leaders[leader2], nil, nil, 4, LEFT, 0.5, nil, nil, nil, nil, nil, true)) then
						otherMembersStr = otherMembersStr .. " " .. TB_MENU_LOCALIZED.GENERALSTRINGAND .. " " .. Clans.Data[clanid].leaders[leader2]
					end
				end
				local otherMembersSize = memberStatusSize - 0.2
				while (not otherMembers:uiText(otherMembersStr, nil, nil, 4, LEFT, otherMembersSize, nil, nil, nil, nil, nil, true)) do
					otherMembersSize = otherMembersSize - 0.05
				end
				otherMembers:addCustomDisplay(true, function()
						otherMembers:uiText(otherMembersStr, nil, nil, 4, CENTER, otherMembersSize)
					end)
			end
		else
			local memberStatusSize = 1
			while (not memberStatus:uiText(TB_MENU_LOCALIZED.CLANSCLANMEMBER, nil, nil, 4, LEFT, memberStatusSize, nil, nil, nil, nil, nil, true)) do
				memberStatusSize = memberStatusSize - 0.05
			end
			memberStatus:addCustomDisplay(true, function()
					memberStatus:uiText(TB_MENU_LOCALIZED.CLANSCLANMEMBER, nil, nil, 4, CENTERMID, memberStatusSize)
				end)
			local otherMembers = UIElement:new({
				parent = clanInfo,
				pos = { 0, clanInfo.size.h / 4 * 3 },
				size = { clanInfo.size.w, clanInfo.size.h / 4 }
			})
			if (Clans.Data[clanid] and #Clans.Data[clanid].members > 1) then
				local member1 = math.random(1, #Clans.Data[clanid].members)
				while (Clans.Data[clanid].members[member1]:lower() == TB_MENU_PLAYER_INFO.username:lower()) do
					member1 = math.random(1, #Clans.Data[clanid].members)
				end
				local otherMembersStr = TB_MENU_LOCALIZED.CLANSTOGETHERWITH .. " " .. Clans.Data[clanid].members[member1]
				if (#Clans.Data[clanid].members > 2) then
					local member2 = math.random(1, #Clans.Data[clanid].members)
					while (Clans.Data[clanid].members[member2]:lower() == TB_MENU_PLAYER_INFO.username:lower() or member2 == member1) do
						member2 = math.random(1, #Clans.Data[clanid].members)
					end
					if (otherMembers:uiText(otherMembersStr .. " " .. TB_MENU_LOCALIZED.GENERALSTRINGAND .. " " .. Clans.Data[clanid].members[member2], nil, nil, 4, LEFT, 0.5, nil, nil, nil, nil, nil, true)) then
						otherMembersStr = otherMembersStr .. " " .. TB_MENU_LOCALIZED.GENERALSTRINGAND .. " " .. Clans.Data[clanid].members[member2]
					end
				end
				local otherMembersSize = memberStatusSize - 0.2
				while (not otherMembers:uiText(otherMembersStr, nil, nil, 4, LEFT, otherMembersSize, nil, nil, nil, nil, nil, true)) do
					otherMembersSize = otherMembersSize - 0.05
				end
				otherMembers:addCustomDisplay(true, function()
						otherMembers:uiText(otherMembersStr, nil, nil, 4, CENTER, otherMembersSize)
					end)
			end
		end
		local clanButton = UIElement:new({
			parent = viewElement,
			pos = { 10, -buttonHeight },
			size = { viewElement.size.w - 20, buttonHeight - 20 },
			interactive = true,
			bgColor = { 0, 0, 0, 0.1 },
			hoverColor = { 0, 0, 0, 0.3 },
			pressedColor = { 1, 0, 0, 0.1 }
		})
		clanButton:addCustomDisplay(false, function()
				clanButton:uiText(TB_MENU_LOCALIZED.CLANSVIEWCLAN)
			end)
		clanButton:addMouseHandlers(nil, function()
				Clans:showClan(viewElement.parent, TB_MENU_PLAYER_INFO.clan.id)
			end)
	else
		local noClanHeader = UIElement:new({
			parent = viewElement,
			pos = { viewElement.size.w / 10, viewElement.size.h / 8 },
			size = { viewElement.size.w / 10 * 8, viewElement.size.h / 4 }
		})
		local noClanHeaderSize = 1
		while (not noClanHeader:uiText(TB_MENU_LOCALIZED.CLANSPLAYERCLANLESS, nil, nil, FONTS.BIG, LEFT, noClanHeaderSize, nil, nil, nil, nil, nil, true)) do
			noClanHeaderSize = noClanHeaderSize - 0.05
		end
		noClanHeader:addCustomDisplay(true, function()
				noClanHeader:uiText(TB_MENU_LOCALIZED.CLANSPLAYERCLANLESS, nil, nil, FONTS.BIG, nil, noClanHeaderSize)
			end)
		local noClanDesc = UIElement:new({
			parent = viewElement,
			pos = { viewElement.size.w / 10, viewElement.size.h / 5 * 2 },
			size = { viewElement.size.w / 10 * 8, viewElement.size.h / 4 }
		})
		local noClanDescSize = 1
		while (not noClanDesc:uiText(TB_MENU_LOCALIZED.CLANSPLAYERCLANLESSINFOMSG, nil, nil, nil, LEFT, noClanDescSize, nil, nil, nil, nil, nil, true)) do
			noClanDescSize = noClanDescSize - 0.05
		end
		noClanDesc:addCustomDisplay(true, function()
				noClanDesc:uiText(TB_MENU_LOCALIZED.CLANSPLAYERCLANLESSINFOMSG, nil, nil, nil, nil, noClanDescSize)
			end)
		local makeNewClan = UIElement:new({
			parent = viewElement,
			pos = { viewElement.size.w / 10, -viewElement.size.h / 4 },
			size = { viewElement.size.w / 10 * 8, viewElement.size.h / 5 },
			bgColor = { 0, 0, 0, 0.3 },
			hoverColor = { 0, 0, 0, 0.5 },
			pressedColor = { 1, 0, 0, 0.1 },
			interactive = true,
			hoverSound = 31
		})
		makeNewClan:addCustomDisplay(false, function()
				makeNewClan:uiText(TB_MENU_LOCALIZED.CLANSCREATENEWCLAN)
			end)
		makeNewClan:addMouseHandlers(nil, function()
				open_url("http://forum.toribash.com/clan_register.php")
			end)
	end
end

function Clans:getDefaultFilters()
	return {
		is_active = { strict = true, val = 2 },
		join_mode = { strict = false, val = 0 },
		is_official = { strict = false, val = false },
		sortby = "rank",
		desc = false
	}
end

function Clans:populateClanList(opt)
	local list = {}
	local options = Clans:getDefaultFilters()
	if (opt) then
		for i,v in pairs(opt) do
			if (i ~= "sortby" and i ~= "desc") then
				options[i].val = v
			else
				options[i] = v
			end
		end
	end
	for _, v in pairs(Clans.Data) do
		local check = true
		for j, z in pairs(options) do
			if (type(z) == "table") then
				if (type(v[j]) == "number" and ((z.strict and z.val ~= v[j]) or (not z.strict and z.val > v[j]))) then
					check = false
					break
				elseif (type(v[j]) == "boolean" and ((z.strict and z.val ~= v[j]) or (not z.strict and z.val == true and v[j] == false))) then
					check = false
					break
				end
			end
		end
		if (check) then
			table.insert(list, v)
		end
	end
	return table.qsort(list, options.sortby, options.desc)
end

function Clans:showClanListFilters(viewElement, opt)
	viewElement:kill(true)
	TB_MENU_SPECIAL_SCREEN_ISOPEN = IGNORE_NAVBAR_SCROLL
	local options = {}
	if (opt) then
		options = opt
	else
		local opts = Clans:getDefaultFilters()
		options = {
			is_active = opts.is_active.val,
			join_mode = opts.join_mode.val,
			is_official = opts.is_official.val,
			sortby = opts.sortby,
			desc = opts.desc
		}
	end

	options.is_active = options.is_active + 1
	options.desc = options.desc and 2 or 1

	local sortOptions = {
		rank = { name = TB_MENU_LOCALIZED.CLANFILTERSRANK },
		name = { name = TB_MENU_LOCALIZED.CLANFILTERSCLANNAME },
		tag = { name = TB_MENU_LOCALIZED.CLANFILTERSCLANTAG },
		id = { name = TB_MENU_LOCALIZED.CLANFILTERSCLANID },
		is_official = { name = TB_MENU_LOCALIZED.CLANFILTERSOFFICIALSTATUS },
		join_mode = { name = TB_MENU_LOCALIZED.CLANFILTERSJOINMODE }
	}
	local activityOptions = {
		{ name = TB_MENU_LOCALIZED.CLANFILTERSDEAD },
		{ name = TB_MENU_LOCALIZED.CLANFILTERSINACTIVE },
		{ name = TB_MENU_LOCALIZED.CLANFILTERSACTIVE }
	}
	local sortOrder = {
		{ name = TB_MENU_LOCALIZED.SORTORDERASCENDING },
		{ name = TB_MENU_LOCALIZED.SORTORDERDESCENDING }
	}
	local optData = {
		--{ opt = "is_active", name = TB_MENU_LOCALIZED.CLANFILTERSACTIVITYSTATE, desc = TB_MENU_LOCALIZED.CLANFILTERSACTIVITYSTATEDESC, customSelection = activityOptions },
		{ opt = "join_mode", name = TB_MENU_LOCALIZED.CLANFILTERSFFAONLY, desc = TB_MENU_LOCALIZED.CLANFILTERSFFAONLYDESC, },
		{ opt = "is_official", name = TB_MENU_LOCALIZED.CLANFILTERSOFFICIALONLY, desc = TB_MENU_LOCALIZED.CLANFILTERSOFFICIALONLYDESC, },
		{ opt = "sortby", name = TB_MENU_LOCALIZED.SORTBYNAME, customSelection = sortOptions },
		{ opt = "desc", name = TB_MENU_LOCALIZED.SORTORDERNAME, customSelection = sortOrder }
	}

	local toReload = UIElement:new({
		parent = viewElement,
		pos = { 0, 0 },
		size = { viewElement.size.w, viewElement.size.h }
	})
	local filtersTopBar = UIElement:new({
		parent = toReload,
		pos = { 0, 0 },
		size = { viewElement.size.w, 50 },
		bgColor = TB_MENU_DEFAULT_DARKER_COLOR,
	})
	local filtersBotBar = UIElement:new({
		parent = toReload,
		pos = { 0, -50 },
		size = { viewElement.size.w, 50 },
		bgColor = TB_MENU_DEFAULT_DARKER_COLOR,
	})
	local filtersTitle = UIElement:new({
		parent = filtersTopBar,
		pos = { 0, 0 },
		size = { filtersTopBar.size.w - filtersTopBar.size.h, filtersTopBar.size.h }
	})
	filtersTitle:addCustomDisplay(true, function()
			filtersTitle:uiText(TB_MENU_LOCALIZED.CLANSSEARCHFILTERS, nil, nil, FONTS.BIG, CENTERMID, 0.7, nil, nil, nil, nil, 0.2)
		end)
	local clanListFilters = TBMenu:createImageButtons(filtersTopBar, filtersTitle.size.w, 0, filtersTitle.size.h, filtersTitle.size.h, TB_MENU_CLANFILTERS_BUTTON, TB_MENU_CLANFILTERS_BUTTON_HOVER, TB_MENU_CLANFILTERS_BUTTON_PRESS)
	clanListFilters:addMouseHandlers(nil, function()
			if (options) then
				options.is_active = options.is_active - 1
				options.desc = options.desc % 2 == 0 and true or false
			end
			Clans:showClanList(viewElement, options)
		end, nil)

	local filtersMain = UIElement:new({
		parent = viewElement,
		pos = { 0, filtersTopBar.size.h },
		size = { filtersTopBar.size.w, viewElement.size.h - filtersTopBar.size.h - filtersBotBar.size.h }
	})
	local filtersView = UIElement:new({
		parent = filtersMain,
		pos = { 0, 0 },
		size = { filtersMain.size.w - 20, filtersMain.size.h }
	})
	local listFilters = {}
	for i,v in pairs(optData) do
		local listFilterElement = UIElement:new({
			parent = filtersView,
			pos = { 0, #listFilters * 50 },
			size = { filtersView.size.w, 50 }
		})
		table.insert(listFilters, listFilterElement)
		local filterName = UIElement:new({
			parent = listFilterElement,
			pos = { 20, 10 },
			size = { (listFilterElement.size.w - 40) / 2, listFilterElement.size.h - 20 }
		})
		filterName:addCustomDisplay(true, function()
				filterName:uiText(optData[i].name, nil, nil, nil, LEFTMID)
			end)
		if (optData[i].desc) then
			local listFilterElement = UIElement:new({
				parent = filtersView,
				pos = { 0, #listFilters * 50 },
				size = { filtersView.size.w, 50 }
			})
			table.insert(listFilters, listFilterElement)
			local filterDesc = UIElement:new({
				parent = listFilterElement,
				pos = { 20, 10 },
				size = { listFilterElement.size.w - 40, listFilterElement.size.h - 20 }
			})
			filterDesc:addCustomDisplay(true, function()
					filterDesc:uiText(optData[i].desc, nil, nil, 4, LEFT, 0.6)
				end)
			if (i ~= #optData) then
				local separator = UIElement:new({
					parent = listFilterElement,
					pos = { 0, -1 },
					size = { listFilterElement.size.w, 1 },
					bgColor = { 0, 0, 0, 0.2 }
				})
			end
			listFilterElement:hide()
		elseif (i ~= #optData) then
			local separator = UIElement:new({
				parent = listFilterElement,
				pos = { 0, -1 },
				size = { listFilterElement.size.w, 1 },
				bgColor = { 0, 0, 0, 0.2 }
			})
		end
		local opts = optData[i].opt
		if (optData[i].customSelection) then
			local optTotal = 0
			for j, k in pairs(optData[i].customSelection) do
				optTotal = optTotal + 1
			end
			local filterOption = UIElement:new({
				parent = listFilterElement,
				pos = { listFilterElement.size.w / 2, 5 },
				size = { (listFilterElement.size.w - 40) / 2, listFilters[i].size.h - 10 },
				bgColor = { 0, 0, 0, 0.3 },
				hoverColor = { 0, 0, 0, 0.5 },
				pressedColor = { 1, 0, 0, 0.1 },
				interactive = true
			})
			local filterSelection = UIElement:new({
				parent = filtersView,
				pos = { filterOption.pos.x - filtersView.pos.x, filterOption.pos.y - filtersView.pos.y },
				size = { filterOption.size.w, filterOption.size.h * optTotal / 3 * 2 },
				bgColor = TB_MENU_DEFAULT_DARKER_COLOR
			})
			filterSelection:addCustomDisplay(false, function()
					if (filterSelection.pos.y < filtersMain.pos.y or filterSelection.pos.y + filterSelection.size.h > filtersMain.pos.y + filtersMain.size.h) then
						filterSelection:moveTo(filterOption.pos.x - filtersView.pos.x, filterOption.pos.y - filtersView.pos.y)
						filterSelection:hide()
					end
				end)
			local count = 0
			for j,k in pairs(optData[i].customSelection) do
				local filterSelectionOption = UIElement:new({
					parent = filterSelection,
					pos = { 0, count * filterOption.size.h / 3 * 2 },
					size = { filterOption.size.w, filterOption.size.h / 3 * 2 },
					interactive = true,
					bgColor = { 0, 0, 0, 0 },
					hoverColor = { 0, 0, 0, 0.2 },
					pressedColor = { 1, 0, 0, 0.1 }
				})
				filterSelectionOption:addCustomDisplay(false, function()
						filterSelectionOption:uiText(k.name, nil, nil, 4, CENTERMID, 0.7)
					end)
				filterSelectionOption:addMouseHandlers(nil, function()
						filterSelection:moveTo(nil, filterOption.pos.y - filtersView.pos.y)
						options[opts] = j
						filterSelection:hide()
					end, nil)
				count = count + 1
			end
			filterOption:addCustomDisplay(false, function()
					filterOption:uiText(optData[i].customSelection[options[opts]].name, nil, nil, nil, CENTERMID, nil, nil, nil, nil, nil, 0.2)
				end)
			filterOption:addMouseHandlers(function()
					if (filterSelection.pos.y + filterSelection.size.h > filtersBotBar.pos.y) then
						local lPos = filtersView:getLocalPos(0, filtersBotBar.pos.y).y
						if (lPos < 0) then
							lPos = lPos - filtersView.size.h
						end
						filterSelection:moveTo(nil, lPos - filterSelection.size.h)
					elseif (filterSelection.pos.y < filtersTopBar.pos.y + filtersTopBar.size.h) then
						local lPos = filtersView:getLocalPos(0, filtersTopBar.pos.y + filtersTopBar.size.h).y
						if (lPos < 0) then
							lPos = lPos - filtersView.size.h
						end
						filterSelection:moveTo(nil, lPos)
					end
					filterSelection:show()
				end, nil, nil)
			filterSelection:hide()
		else
			local filterCheckbox = UIElement:new({
				parent = listFilterElement,
				pos = { -60, 5 },
				size = { listFilterElement.size.h - 10, listFilterElement.size.h - 10 },
				bgColor = { 0, 0, 0, 0.3 },
				hoverColor = { 0, 0, 0, 0.5 },
				pressedColor = { 1, 0, 0, 0.1 },
				interactive = true
			})
			local filterCheckboxIcon = UIElement:new({
				parent = filterCheckbox,
				pos = { 0, 0 },
				size = { filterCheckbox.size.w, filterCheckbox.size.h },
				bgImage = "../textures/menu/general/buttons/checkmark.tga"
			})
			if (options[opts] == 0 or options[opts] == false) then
				filterCheckboxIcon:hide(true)
			end
			filterCheckbox:addMouseHandlers(nil, function()
					if (type(options[opts]) == "boolean") then
						options[opts] = not options[opts]
					else
						options[opts] = 1 - options[opts]
					end
					if (options[opts] == 1 or options[opts] == true) then
						filterCheckboxIcon:show(true)
					else
						filterCheckboxIcon:hide(true)
					end
				end, nil)
		end
	end

	for i,v in pairs(listFilters) do
		v:hide()
	end

	local filtersScrollBar = TBMenu:spawnScrollBar(filtersView, #listFilters, 50)
	filtersView.scrollBar = filtersScrollBar
	filtersScrollBar:makeScrollBar(filtersView, listFilters, toReload)

	local clanFiltersBotSmudge = TBMenu:addBottomBloodSmudge(filtersBotBar, 2)
	local filterSearchButton = UIElement:new({
		parent = filtersBotBar,
		pos = { filtersBotBar.size.w / 6, 5 },
		size = { filtersBotBar.size.w / 6 * 4, filtersBotBar.size.h - 10 },
		interactive = true,
		bgColor = { 0, 0, 0, 0.1 },
		hoverColor = { 0, 0, 0, 0.3 },
		pressedColor = { 1, 0, 0, 0.1 },
		hoverSound = 31
	})
	filterSearchButton:addCustomDisplay(false, function()
			filterSearchButton:uiText(TB_MENU_LOCALIZED.CLANSSEARCH, nil, nil, FONTS.BIG, CENTERMID, 0.5)
		end)
	filterSearchButton:addMouseHandlers(nil, function()
			options.is_active = options.is_active - 1
			options.desc = options.desc % 2 == 0 and true or false
			CLANLISTSHIFT[1] = 0
			Clans:showClanList(viewElement, options)
		end, nil)
end

function Clans:showClanList(viewElement, options)
	viewElement:kill(true)
	TB_MENU_SPECIAL_SCREEN_ISOPEN = 0
	if (CLANSEARCHFILTERS and type(CLANSEARCHFILTERS.desc) ~= "boolean") then
		CLANSEARCHFILTERS.is_active = CLANSEARCHFILTERS.is_active - 1
		CLANSEARCHFILTERS.desc = CLANSEARCHFILTERS.desc % 2 == 0 and true or false
	end
	local options = options or CLANSEARCHFILTERS
	local clanList = Clans:populateClanList(options)
	CLANSEARCHFILTERS = options
	local clanEntryHeight = 45
	-- Parent Object to hold all elements that require reloading when scrolling
	local toReload = UIElement:new({
		parent = viewElement,
		pos = { 0, 0 },
		size = { viewElement.size.w, viewElement.size.h }
	})

	-- Top and Bottom bars, keep interactive to prevent clicking through
	local clanListTopBar = UIElement:new({
		parent = toReload,
		pos = { 0, 0 },
		size = { viewElement.size.w, 80 },
		bgColor = TB_MENU_DEFAULT_DARKER_COLOR,
		interactive = true
	})
	local clanListTopBarTitle = UIElement:new({
		parent = clanListTopBar,
		pos = { 0, 0 },
		size = { clanListTopBar.size.w - 50, 50 }
	})
	clanListTopBarTitle:addCustomDisplay(true, function()
			clanListTopBarTitle:uiText(TB_MENU_LOCALIZED.CLANSCLANLIST, nil, nil, FONTS.BIG, CENTERMID, 0.7, nil, nil, nil, nil, 0.2)
		end)
	local clanListFilters = TBMenu:createImageButtons(clanListTopBar, clanListTopBarTitle.size.w, 0, clanListTopBarTitle.size.h, clanListTopBarTitle.size.h, TB_MENU_CLANFILTERS_BUTTON, TB_MENU_CLANFILTERS_BUTTON_HOVER, TB_MENU_CLANFILTERS_BUTTON_PRESS)
	clanListFilters:addMouseHandlers(nil, function()
			Clans:showClanListFilters(viewElement, options)
		end, nil)

	local clanListLegendRankWidth = 60
	local clanListLegendNameWidth = (clanListTopBar.size.w - clanListLegendRankWidth - 30) / 5 * 3
	local clanListLegendOfficialWidth = (clanListTopBar.size.w - clanListLegendRankWidth - 30) / 5
	local clanListLegendJoinModeWidth = (clanListTopBar.size.w - clanListLegendRankWidth - 30) / 5

	local clanListTopBarLegend = UIElement:new({
		parent = clanListTopBar,
		pos = { 0, clanListTopBarTitle.size.h },
		size = { clanListTopBar.size.w, clanListTopBar.size.h - clanListTopBarTitle.size.h },
		bgColor = TB_MENU_DEFAULT_DARKER_COLOR,
	})
	local clanListLegendRank = UIElement:new({
		parent = clanListTopBarLegend,
		pos = { 0, 0 },
		size = { clanListLegendRankWidth, clanListTopBarLegend.size.h },
		bgColor = { 0, 0, 0, 0.05 }
	})
	clanListLegendRank:addCustomDisplay(false, function()
			clanListLegendRank:uiText(TB_MENU_LOCALIZED.CLANSLEGENDRANK, nil, nil, 4, CENTERMID, 0.7)
		end)
	local clanListLegendName = UIElement:new({
		parent = clanListTopBarLegend,
		pos = { clanListLegendRankWidth, 0 },
		size = { clanListLegendNameWidth, clanListTopBarLegend.size.h }
	})
	clanListLegendName:addCustomDisplay(true, function()
			clanListLegendName:uiText(TB_MENU_LOCALIZED.CLANSLEGENDTAGNAME, nil, nil, 4, CENTERMID, 0.7)
		end)
	local clanListLegendOfficial = UIElement:new({
		parent = clanListTopBarLegend,
		pos = { clanListLegendRankWidth + clanListLegendNameWidth, 0 },
		size = { clanListLegendOfficialWidth, clanListTopBarLegend.size.h },
		bgColor = { 0, 0, 0, 0.05 }
	})
	clanListLegendOfficial:addCustomDisplay(false, function()
			clanListLegendOfficial:uiText(TB_MENU_LOCALIZED.CLANSLEGENDSTATUS, nil, nil, 4, CENTERMID, 0.7)
		end)
	local clanListLegendJoinMode = UIElement:new({
		parent = clanListTopBarLegend,
		pos = { clanListLegendRankWidth + clanListLegendNameWidth + clanListLegendOfficialWidth, 0 },
		size = { clanListLegendJoinModeWidth, clanListTopBarLegend.size.h }
	})
	clanListLegendJoinMode:addCustomDisplay(true, function()
			clanListLegendJoinMode:uiText(TB_MENU_LOCALIZED.CLANSLEGENDJOINMODE, nil, nil, 4, CENTERMID, 0.7)
		end)
	local clanListBotBar = UIElement:new({
		parent = toReload,
		pos = { 0, -30 },
		size = { viewElement.size.w, 30 },
		bgColor = TB_MENU_DEFAULT_DARKER_COLOR,
		interactive = true
	})
	local clanListBotSmudge = TBMenu:addBottomBloodSmudge(clanListBotBar, 2)

	-- Main View for Clan List
	local clanListView = UIElement:new({
		parent = viewElement,
		pos = { 0, clanListTopBar.size.h },
		size = { viewElement.size.w, viewElement.size.h - clanListTopBar.size.h - clanListBotBar.size.h }
	})

	-- Clan Holder Object, used to create scrollable list
	local clanListHolder = UIElement:new({
		parent = clanListView,
		pos = { 0, 0 },
		size = { clanListView.size.w - 20, clanListView.size.h }
	})

	if (#clanList > 0) then
		local clanListClans = {}
		for i, v in pairs(clanList) do
			clanListClans[i] = UIElement:new({
				parent = clanListHolder,
				pos = { 0, (i - 1) * clanEntryHeight },
				size = { clanListHolder.size.w, clanEntryHeight },
				interactive = true,
				bgColor = { 0, 0, 0, i % 2 == 0 and 0 or 0.1 },
				hoverColor = { 0, 0, 0, 0.3 },
				pressedColor = { 0, 0, 0, 0.4 },
				hoverSound = 31
			})
			clanListClans[i]:addMouseHandlers(nil, function()
					Clans:showClan(viewElement.parent, clanList[i].id)
				end, nil)
			local clanListClanRank = UIElement:new({
				parent = clanListClans[i],
				pos = { 0, 0 },
				size = { clanListLegendRankWidth, clanListClans[i].size.h },
				bgColor = { 0, 0, 0, 0.05 }
			})
			local clanRank = clanList[i].rank == 0 and "-" or clanList[i].rank
			clanListClanRank:addCustomDisplay(false, function()
					clanListClanRank:uiText(clanRank, nil, nil, 4, CENTERMID, 0.7)
				end)
			local clanListClanNameView = UIElement:new({
				parent = clanListClans[i],
				pos = { clanListLegendRankWidth, 0 },
				size = { clanListLegendNameWidth, clanListClans[i].size.h }
			})
			local clanListClanTag = UIElement:new({
				parent = clanListClanNameView,
				pos = { 0, 0 },
				size = { clanListClanNameView.size.w / 3 - 5, clanListClanNameView.size.h }
			})
			local clanListClanName = UIElement:new({
				parent = clanListClanNameView,
				pos = { clanListClanNameView.size.w / 3 + 5, 0 },
				size = { clanListClanNameView.size.w / 3 * 2 - 5, clanListClanNameView.size.h }
			})
			local clanListClanNameSeparator = UIElement:new({
				parent = clanListClanNameView,
				pos = { clanListClanNameView.size.w / 3 - 5, 0 },
				size = { 10, clanListClanNameView.size.h }
			})
			clanListClanNameSeparator:addCustomDisplay(true, function()
					clanListClanNameSeparator:uiText("|", nil, nil, 4, CENTERMID, 0.7)
				end)
			clanListClanTag:addCustomDisplay(true, function()
					clanListClanTag:uiText(clanList[i].tag, nil, nil, 4, RIGHTMID, 0.7)
				end)
			clanListClanName:addCustomDisplay(true, function()
					clanListClanName:uiText(clanList[i].name, nil, nil, 4, LEFTMID, 0.7)
				end)
			local clanListClanOfficial = UIElement:new({
				parent = clanListClans[i],
				pos = { clanListLegendRankWidth + clanListLegendNameWidth, 0 },
				size = { clanListLegendOfficialWidth, clanListClans[i].size.h },
				bgColor = { 0, 0, 0, 0.05 }
			})
			local officialStatus = clanList[i].is_official == 1 and TB_MENU_LOCALIZED.CLANSTATEOFFICIAL or TB_MENU_LOCALIZED.CLANSTATEUNOFFICIAL
			clanListClanOfficial:addCustomDisplay(false, function()
					clanListClanOfficial:uiText(officialStatus, nil, nil, 4, CENTERMID, 0.7)
				end)
			local clanListClanJoinMode = UIElement:new({
				parent = clanListClans[i],
				pos = { clanListLegendRankWidth + clanListLegendNameWidth + clanListLegendOfficialWidth, 0 },
				size = { clanListLegendJoinModeWidth, clanListClans[i].size.h }
			})
			local joinModeStatus = clanList[i].join_mode == 1 and TB_MENU_LOCALIZED.CLANSTATEFREEFORALL or TB_MENU_LOCALIZED.CLANSTATEINVITEONLY
			clanListClanJoinMode:addCustomDisplay(true, function()
					clanListClanJoinMode:uiText(joinModeStatus, nil, nil, 4, CENTERMID, 0.7)
				end)
			clanListClans[i]:hide()
		end

		local clanListScrollBG = UIElement:new({
			parent = clanListView,
			pos = { -(clanListView.size.w - clanListHolder.size.w), 0 },
			size = { clanListView.size.w - clanListHolder.size.w, clanListHolder.size.h },
			bgColor = TB_MENU_DEFAULT_DARKER_COLOR
		})
		local clanListScrollBar = TBMenu:spawnScrollBar(clanListHolder, #clanListClans, clanEntryHeight)
		clanListHolder.scrollBar = clanListScrollBar
		clanListScrollBar:makeScrollBar(clanListHolder, clanListClans, toReload, CLANLISTSHIFT)
	else
		clanListHolder:addCustomDisplay(true, function()
			clanListHolder:uiText(TB_MENU_LOCALIZED.CLANSLISTEMPTYMSG, nil, nil, 4)
		end)
	end
end

function Clans:showClanInfoLeft(viewElement, clanid)
	TBMenu:addBottomBloodSmudge(viewElement, 2)
	local clanName = UIElement:new({
		parent = viewElement,
		pos = { 10, 10 },
		size = { viewElement.size.w - 20, 60 }
	})
	local clanTag = Clans.Data[clanid].is_official == 1 and "[" .. Clans.Data[clanid].tag .. "]" or "(" .. Clans.Data[clanid].tag .. ")"
	clanName:addAdaptedText(true, clanTag .. " " .. Clans.Data[clanid].name, nil, nil, FONTS.BIG, nil, 0.6, nil, 0.2)
	local joinInteractive = false
	if (Clans.Data[clanid].join_mode == 1 and TB_MENU_PLAYER_INFO.clan.id ~= 0 and (Clans.Data[clanid].members_total < Clans.Levels[math.min(#Clans.Levels, Clans.Data[clanid].level + 1)].max_members or Clans:isBeginnerClan(clanid))) then
		joinInteractive = true
	end
	local clanJoin = UIElement:new({
		parent = viewElement,
		pos = { 10, -80 },
		size = { viewElement.size.w - 20, 70 },
		interactive = joinInteractive,
		bgColor = { 0, 0, 0, 0.1 },
		hoverColor = { 0, 0, 0, 0.3 },
		pressedColor = { 1, 0, 0, 0.1 }
	})
	if (joinInteractive) then
		clanJoin:addAdaptedText(false, TB_MENU_LOCALIZED.CLANSJOINCLAN)
		clanJoin:addMouseHandlers(nil, function()
				open_url("http://forum.toribash.com/clan.php?clanid=" .. clanid .. "&join=1")
			end)
	elseif (Clans.Data[clanid].join_mode == 1) then
		clanJoin:addAdaptedText(false, TB_MENU_LOCALIZED.CLANSTATEFREEFORALL, nil, nil, nil, nil, nil, nil, 0.2)
	else
		clanJoin:addAdaptedText(false, TB_MENU_LOCALIZED.CLANSTATEINVITEONLY, nil, nil, nil, nil, nil, nil, 0.2)
	end

	local freeSpace = viewElement.size.h - clanName.shift.y - clanName.size.h - clanJoin.size.h - 30
	local logoScale = 256 > freeSpace and freeSpace or 256
	local clanLogo = UIElement:new({
		parent = viewElement,
		pos = { (viewElement.size.w - logoScale) / 2, clanName.size.h + clanName.shift.y + 10 + (freeSpace - logoScale) / 2 },
		size = { logoScale, logoScale },
		bgImage =  { "../textures/clans/"..clanid..".tga", Clans.DefaultLogo }
	})
	Clans:loadClanLogo(clanid, clanLogo)
	local logoReload = UIElement:new({
		parent = clanLogo,
		pos = { 0, 0 },
		size = { clanLogo.size.w, clanLogo.size.h },
		interactive = true,
		bgColor = { 0, 0, 0, 0 },
		hoverColor = { 0, 0, 0, 0.3 },
		pressedColor = { 1, 0, 0, 0.1 }
	})
	logoReload:addCustomDisplay(true, function()
			local color = logoReload:getButtonColor()
			set_color(unpack(color))
			draw_quad(logoReload.pos.x, logoReload.pos.y, logoReload.size.w, logoReload.size.h)
			logoReload:uiText(TB_MENU_LOCALIZED.CLANSRELOADLOGO, nil, nil, nil, nil, nil, nil, nil, {1, 1, 1, color[4] * 2} )
		end)
	logoReload:addMouseHandlers(nil, function()
			Clans:loadClanLogo(clanid, clanLogo, true)
		end, nil)
end

function Clans:showClanInfoMid(viewElement, clanid)
	local clanLevelValue = Clans.Data[clanid].level
	local clanTopAch = Clans.Data[clanid].top_achievement
	local xpBarProgress = 0
	if (clanLevelValue < #Clans.Levels) then
		xpBarProgress = (Clans.Data[clanid].xp - Clans.Levels[clanLevelValue].min_xp) / (Clans.Levels[clanLevelValue + 1].min_xp - Clans.Levels[clanLevelValue].min_xp)
		if (xpBarProgress > 1) then
			xpBarProgress = 1
		end
	else
		xpBarProgress = 1
	end

	TBMenu:addBottomBloodSmudge(viewElement, 1)
	local clanRank = UIElement:new( {
		parent = viewElement,
		pos = { 40, 10 },
		size = { (viewElement.size.w - 80) / 2, 35 }
	})
	local clanRankText = TB_MENU_LOCALIZED.CLANSLEGENDRANK .. " "..Clans.Data[clanid].rank
	if (Clans.Data[clanid].rank < 1) then
		clanRankText = TB_MENU_LOCALIZED.CLANSTATEUNRANKED
	end
	clanRank:addAdaptedText(true, clanRankText, nil, nil, FONTS.BIG, LEFTMID, nil, nil, 0.2)
	local clanLevel = UIElement:new({
		parent = viewElement,
		pos = { viewElement.size.w / 2, 10 },
		size = { (viewElement.size.w - 80) / 2, 35}
	})
	clanLevel:addAdaptedText(false, TB_MENU_LOCALIZED.CLANSLEGENDLEVEL .. " " .. clanLevelValue, nil, nil, FONTS.BIG, RIGHTMID, nil, nil, 0.2)
	local clanXpBarOutline = UIElement:new( {
		parent = viewElement,
		pos = { 30, 50 },
		size = { viewElement.size.w - 60, 60 },
		bgColor = { 0.1, 0.1, 0.1, 0.5 },
		shapeType = ROUNDED,
		rounded = 10
	})
	local clanXpBar = UIElement:new({
		parent = clanXpBarOutline,
		pos = { 2, 2 },
		size = { clanXpBarOutline.size.w - 4, clanXpBarOutline.size.h - 4 },
		bgColor = Clans.Data[clanid].xpBarBgColor or { 0.5, 0.1, 0.1, 1 },
		shapeType = clanXpBarOutline.shapeType,
		rounded = clanXpBarOutline.rounded / 5 * 4 })
	if (xpBarProgress > 0) then
		clanXpBar:addChild({
			size = { clanXpBar.size.w * xpBarProgress, clanXpBar.size.h },
			bgColor = Clans.Data[clanid].xpBarColor or { 0.78, 0.05, 0.08, 1 },
			innerShadow = { 4, 4 },
			shadowColor = { Clans.Data[clanid].xpBarAccentTopColor or { 0.91, 0.34, 0.24, 1 }, Clans.Data[clanid].xpBarAccentBotColor or { 0.33, 0, 0, 1 } }
		}, true)
	end

	local clanXp = UIElement:new( {
		parent = clanXpBar,
		pos = { 0, 0 },
		size = { clanXpBar.size.w, clanXpBar.size.h } } )
	local clanXpStr = Clans.Data[clanid].xp
	if (clanLevelValue < #Clans.Levels) then
		clanXpStr = clanXpStr .. " / " .. Clans.Levels[clanLevelValue + 1].min_xp .. " " .. TB_MENU_LOCALIZED.CLANSLEGENDXP
	else
		clanXpStr = clanXpStr .. " " .. TB_MENU_LOCALIZED.CLANSLEGENDXP
	end
	clanXp:addAdaptedText(false, clanXpStr, nil, nil, FONTS.BIG, nil, 0.65, nil, nil, 2)
	local clanWars = UIElement:new({
		parent = viewElement,
		pos = { 30, 120 },
		size = { viewElement.size.w - 60, (viewElement.size.h - 140) / 2 },
		interactive = true,
		bgColor = { 0, 0, 0, 0.1 },
		hoverColor = { 0, 0, 0, 0.3 },
		pressedColor = { 1, 0, 0, 0.1 }
	})
	clanWars:addAdaptedText(false, TB_MENU_LOCALIZED.CLANSVIEWWARSFORUM, nil, nil, FONTS.BIG, nil, 0.8, nil, 0.6)
	clanWars:addMouseHandlers(nil, function()
			open_url("http://forum.toribash.com/clan_war.php?clanid=" .. clanid)
		end)
	local clanTopAchievement = UIElement:new({
		parent = viewElement,
		pos = { 30, -(viewElement.size.h - 120) / 2 },
		size = { viewElement.size.w - 60, (viewElement.size.h - 140) / 2 }
	})
	if (clanTopAch ~= 0) then
		local iconScale = clanTopAchievement.size.h >= 110 and 100 or clanTopAchievement.size.h - 10
		local clanTopAchIcon = UIElement:new({
			parent = clanTopAchievement,
			pos = { 10, (clanTopAchievement.size.h - iconScale) / 2 },
			size = { iconScale, iconScale },
			bgImage = "../textures/clans/achievements/" .. clanTopAch .. ".tga"
		})
		local clanTopAchName = UIElement:new({
			parent = clanTopAchievement,
			pos = { iconScale + 10, 0 },
			size = { clanTopAchievement.size.w - iconScale - 20, clanTopAchievement.size.h / 2 - 5 }
		})
		clanTopAchName:addCustomDisplay(false, function()
			clanTopAchName:uiText(Clans.Achievements[clanTopAch].name, nil, nil, nil, CENTERBOT)
		end)
		local clanTopAchDesc = UIElement:new({
			parent = clanTopAchievement,
			pos = { iconScale + 30, clanTopAchievement.size.h / 2 + 5 },
			size = { clanTopAchievement.size.w - iconScale - 60, clanTopAchievement.size.h / 2 - 5 },
		})
		clanTopAchDesc:addCustomDisplay(false, function()
			clanTopAchDesc:uiText(Clans.Achievements[clanTopAch].description, nil, nil, 4, CENTER, 0.7)
		end)
	else
		local clanTopAchDesc = UIElement:new({
			parent = clanTopAchievement,
			pos = { 10, 0 },
			size = { clanTopAchievement.size.w - 20, clanTopAchievement.size.h }
		})
		clanTopAchDesc:addCustomDisplay(false, function()
				clanTopAchDesc:uiText(TB_MENU_LOCALIZED.CLANSTOPACHMISSING, nil, nil, 4, nil, 0.7)
			end)
	end
end

---@class ClansPlayerHeadPreview : UIElement3D
---@field player string Player's name

---Helper function that will be called recursively to download and set head avatars for clan members
---@param reloader UIElement
---@param avatars ClansPlayerHeadPreview[]
---@param id integer
function Clans.downloadHead(reloader, avatars, id)
	local downloads = get_downloads()
	if (#downloads == 0) then
		local customs = PlayerInfo:getItems(avatars[id].player, PLAYERINFO_CSCOPE_TEXTURES)
		if (customs.textures.head.equipped) then
			avatars[id]:updateImage("../../custom/" .. avatars[id].player:lower() .. "/head.tga", nil, true)
		end
		if (id < #avatars) then
			id = id + 1
			download_head(avatars[id].player)
			reloader:addCustomDisplay(false, function() Clans.downloadHead(reloader, avatars, id) end)
		else
			reloader:kill()
		end
	end
end

---Downloads and resets head avatars for the provided elements
---@param avatars ClansPlayerHeadPreview[]
function Clans:reloadHeadAvatars(avatars)
	for i = #avatars, 1, -1 do
		if (avatars[i].player == TB_MENU_PLAYER_INFO.username) then
			table.remove(avatars, i)
			break
		end
	end
	if (#avatars > 0) then
		if (avatars[1].player) then
			download_head(avatars[1].player)
		end
		local reloader = UIElement:new({
			parent = TBMenu.CurrentSection,
			pos = { 0, 0 },
			size = { 1, 1 }
		})
		reloader:addCustomDisplay(false, function() Clans.downloadHead(reloader, avatars, 1) end)
	end
end

function Clans:showPlayerAvatar(parent, avatarWidth, user)
	local avatarViewport = UIElement:new( {
		parent = parent,
		pos = { 0, 0 },
		size = { avatarWidth, avatarWidth },
		viewport = true
	})
	local avatarViewport3D = UIElement3D:new({
		globalid = TB_MENU_MAIN_GLOBALID,
		shapeType = VIEWPORT,
		parent = avatarViewport,
		pos = { 0, 0, 0 },
		size = { 0, 0, 0 },
		rot = { 0, 0, 0 },
		viewport = true
	})
	table.insert(avatarViewport.child, avatarViewport3D)
	local headTexture = { "../../custom/tori/head.tga", "../../custom/tori/head.tga" }
	local player = PlayerInfo:getItems(user, PLAYERINFO_CSCOPE_TEXTURES)
	if (player.textures.head.equipped) then
		headTexture[1] = "../../custom/" .. user .. "/head.tga"
	end
	local avatar = UIElement3D:new({
		parent = avatarViewport3D,
		shapeType = SPHERE,
		pos = { 0, 0, 10 },
		rot = { 0, 0, 0 },
		size = { 1, 0, 0 },
		bgColor = { 1, 1, 1, 1 },
		bgImage = headTexture,
		viewport = true
	})
	avatar.player = user
	return avatar
end

function Clans:showClanMemberlist(viewElement, clanid)
	local rosterEntryHeight = 40
	local avatarWidth = rosterEntryHeight

	local toReload, rosterTop, rosterBottom, rosterView, rosterMemberHolder, rosterScrollBG = TBMenu:prepareScrollableList(viewElement, 50, rosterEntryHeight, 15, Clans.Data[clanid].bgColor)
	local rosterTitle = UIElement:new({
		parent = rosterTop,
		pos = { avatarWidth, 0 },
		size = { rosterTop.size.w - avatarWidth * 2, rosterTop.size.h }
	})
	local rosterStr = TB_MENU_LOCALIZED.CLANSLEGENDROSTER .. (Clans:isBeginnerClan(clanid) and (" (" .. Clans.Data[clanid].members_total .. ")") or (" (" .. Clans.Data[clanid].members_total .. "/" .. Clans.Levels[Clans.Data[clanid].level].max_members .. ")"))
	rosterTitle:addAdaptedText(true, rosterStr, nil, nil, FONTS.BIG, nil, nil, nil, 0)

	local viewportTopReplacer = UIElement:new( {
		parent = rosterTop,
		pos = { 0, 0 },
		size = { avatarWidth, rosterTop.size.h },
		viewport = true
	})
	local viewportTopReplacer3D = UIElement3D:new({
		globalid = TB_MENU_MAIN_GLOBALID,
		shapeType = VIEWPORT,
		parent = viewportTopReplacer,
		pos = { 0, 0, 0 },
		size = { 0, 0, 0 },
		rot = { 0, 0, 0 },
		viewport = true
	})
	table.insert(viewportTopReplacer.child, viewportTopReplacer3D)
	if (get_option("shaders") == 1) then
		local cube = UIElement3D:new({
			parent = viewportTopReplacer3D,
			pos = { 0, 0, 10 },
			size = { 2, 2, 2 },
			bgColor = Clans.Data[clanid].bgColor or TB_MENU_DEFAULT_DARKER_COLOR,
			viewport = true
		})
		local viewportBotReplacer = UIElement:new( {
			parent = rosterBottom,
			pos = { 0, 0 },
			size = { avatarWidth, avatarWidth },
			viewport = true
		})
		local viewportBotReplacer3D = UIElement3D:new({
			globalid = TB_MENU_MAIN_GLOBALID,
			shapeType = VIEWPORT,
			parent = viewportBotReplacer,
			pos = { 0, 0, 0 },
			size = { 0, 0, 0 },
			rot = { 0, 0, 0 },
			viewport = true
		})
		table.insert(viewportBotReplacer.child, viewportBotReplacer3D)
		local cube2 = UIElement3D:new({
			parent = viewportBotReplacer3D,
			pos = { 0, 0, 10 },
			size = { 2, 2, 2 },
			bgColor = Clans.Data[clanid].bgColor or TB_MENU_DEFAULT_DARKER_COLOR,
			viewport = true
		})
	end
	TBMenu:addBottomBloodSmudge(rosterBottom, 3)

	local rosterMembers = {}
	local headAvatars = {}
	local rosterPos = 0
	if (#Clans.Data[clanid].leaders > 0) then
		local leadersTitle = UIElement:new({
			parent = rosterMemberHolder,
			pos = { 0, rosterPos },
			size = { rosterMemberHolder.size.w, rosterEntryHeight }
		})
		table.insert(rosterMembers, leadersTitle)
		rosterPos = rosterPos + rosterEntryHeight
		local leaderStr = utf8.len(Clans.Data[clanid].leaderscustom) > 0 and Clans.Data[clanid].leaderscustom or (#Clans.Data[clanid].leaders > 1 and TB_MENU_LOCALIZED.CLANLEADERS or TB_MENU_LOCALIZED.CLANLEADER)
		leadersTitle:addAdaptedText(true, leaderStr, nil, nil, nil, nil, nil, nil, 0.2)
		for _, v in pairs(Clans.Data[clanid].leaders) do
			local leader = UIElement:new({
				parent = rosterMemberHolder,
				pos = { 0, rosterPos },
				size = { rosterMemberHolder.size.w, rosterEntryHeight },
				bgColor = rosterPos % (rosterEntryHeight * 2 ) == 0 and { 0, 0, 0, 0.1 } or { 0, 0, 0, 0 }
			})
			table.insert(headAvatars, Clans:showPlayerAvatar(leader, avatarWidth, v))
			local leaderText = UIElement:new({
				parent = leader,
				pos = { avatarWidth + 5, 0 },
				size = { leader.size.w - avatarWidth - 10, leader.size.h }
			})
			leaderText:addAdaptedText(true, v, nil, nil, 4, LEFTMID, 0.7)
			table.insert(rosterMembers, leader)
			rosterPos = rosterPos + rosterEntryHeight
		end
	end
	if (#Clans.Data[clanid].members > 0) then
		local membersTitle = UIElement:new({
			parent = rosterMemberHolder,
			pos = { 0, rosterPos },
			size = { rosterMemberHolder.size.w, rosterEntryHeight }
		})
		table.insert(rosterMembers, membersTitle)
		rosterPos = rosterPos + rosterEntryHeight
		local memberStr = utf8.len(Clans.Data[clanid].memberscustom) > 0 and Clans.Data[clanid].memberscustom or (#Clans.Data[clanid].members > 1 and TB_MENU_LOCALIZED.CLANMEMBERS or TB_MENU_LOCALIZED.CLANMEMBER)
		membersTitle:addAdaptedText(true, memberStr, nil, nil, nil, nil, nil, nil, 0.2)
		for _, v in pairs(Clans.Data[clanid].members) do
			local member = UIElement:new({
				parent = rosterMemberHolder,
				pos = { 0, rosterPos },
				size = { rosterMemberHolder.size.w, rosterEntryHeight },
				bgColor = rosterPos % (rosterEntryHeight * 2 ) == 0 and { 0, 0, 0, 0.05 } or { 0, 0, 0, 0 }
			})
			table.insert(headAvatars, Clans:showPlayerAvatar(member, avatarWidth, v))
			local memberText = UIElement:new({
				parent = member,
				pos = { avatarWidth + 5, 0 },
				size = { member.size.w - avatarWidth - 10, member.size.h }
			})
			memberText:addAdaptedText(true, v, nil, nil, 4, LEFTMID, 0.7)
			table.insert(rosterMembers, member)
			rosterPos = rosterPos + rosterEntryHeight
		end
	end

	if (#rosterMembers > 0) then
		Clans:reloadHeadAvatars(headAvatars)

		for _, v in pairs(rosterMembers) do
			v:hide()
		end

		local rosterScrollBar = TBMenu:spawnScrollBar(rosterMemberHolder, #rosterMembers, rosterEntryHeight)
		rosterMemberHolder.scrollBar = rosterScrollBar
		rosterScrollBar:makeScrollBar(rosterMemberHolder, rosterMembers, toReload)
	else
		local clanMembersEmpty = UIElement:new({
			parent = rosterView,
			pos = { 0, 0 },
			size = { rosterView.size.w, rosterView.size.h }
		})
		clanMembersEmpty:addCustomDisplay(true, function()
				clanMembersEmpty:uiText(TB_MENU_LOCALIZED.CLANSMEMBERSEMPTY)
			end)
	end
end

function Clans:showClan(viewElement, clanid)
	TB_MENU_SPECIAL_SCREEN_ISOPEN = IGNORE_NAVBAR_SCROLL
	TB_MENU_CLANS_OPENCLANID = clanid
	TBMenu:clearNavSection()
	TBMenu:showNavigationBar(Clans:getNavigationButtons(true), true)

	Clans.Data[clanid] = Clans.Data[clanid] or { }
	local clanView = UIElement:new({
		parent = viewElement,
		pos = { 0, 0 },
		size = { viewElement.size.w, viewElement.size.h },
		uiColor = Clans.Data[clanid].colorNegative and UICOLORBLACK or UICOLORWHITE,
		uiShadowColor = Clans.Data[clanid].colorNegative and UICOLORWHITE or UICOLORBLACK,
	})
	local clanInfoLeftView = UIElement:new({
		parent = clanView,
		pos = { 5, 0 },
		size = { 276, clanView.size.h },
		bgColor = Clans.Data[clanid].bgColor or TB_MENU_DEFAULT_BG_COLOR
	})
	Clans:showClanInfoLeft(clanInfoLeftView, clanid)
	local memberlistWidth = (clanView.size.w - clanInfoLeftView.size.w - 30) / 3 * 2 < 200 and 200 or (clanView.size.w - clanInfoLeftView.size.w - 30) / 3
	memberlistWidth = memberlistWidth > 276 and 276 or memberlistWidth
	local clanInfoMemberlistView = UIElement:new({
		parent = clanView,
		pos = { -memberlistWidth - 5, 0 },
		size = { memberlistWidth, clanView.size.h },
		bgColor = Clans.Data[clanid].bgColor or TB_MENU_DEFAULT_BG_COLOR
	})
	Clans:showClanMemberlist(clanInfoMemberlistView, clanid)
	local clanInfoMidView = UIElement:new({
		parent = clanView,
		pos = { clanInfoLeftView.size.w + clanInfoLeftView.shift.x + 10, 0 },
		size = { clanView.size.w - clanInfoLeftView.size.w - clanInfoMemberlistView.size.w - 30, clanView.size.h },
		bgColor = Clans.Data[clanid].bgColor or TB_MENU_DEFAULT_BG_COLOR
	})
	Clans:showClanInfoMid(clanInfoMidView, clanid)
end

function Clans:loadClanLogo(clanid, viewElement, reload)
	for i = #LOGOCACHE, 1, -1 do
		if (LOGOCACHE[i] == clanid) then
			if (reload) then
				table.remove(LOGOCACHE, i)
				break
			else
				return
			end
		end
	end

	download_clan_logo(clanid)
	local rotation = 0
	local scale = 0
	local transparency = { 0.8 }
	local loadView = UIElement:new({
		parent = viewElement,
		pos = { 0, -30 },
		size = { viewElement.size.w, 30 }
	})
	loadView:addCustomDisplay(true, function()
			set_color(0, 0, 0, transparency[1] / 2)
			draw_quad(loadView.pos.x, loadView.pos.y, loadView.size.w, loadView.size.h)
		end)
	local loadIndicatorDisk = UIElement:new({
		parent = loadView,
		pos = { 0, 0 },
		size = { loadView.size.h,  loadView.size.h }
	})
	local loadIndicator = UIElement:new({
		parent = loadView,
		pos = { loadView.size.h, 0 },
		size = { loadView.size.w - loadView.size.h, loadView.size.h }
	})
	loadIndicatorDisk:addCustomDisplay(true, function()
			set_color(1,1,1,transparency[1])
			draw_disk(loadIndicatorDisk.pos.x + loadIndicatorDisk.size.w / 2, loadIndicatorDisk.pos.y + loadIndicatorDisk.size.h / 2, 6, 12, 200, 1, rotation, scale, 0)
			rotation = rotation + 2.5
			scale = scale + 5
			if (scale > 360) then
				scale = -360
			end
		end)
	local updateTextScale = 1
	while (not loadIndicator:uiText(TB_MENU_LOCALIZED.CLANSUPDATINGLOGO, nil, nil, nil, LEFT, updateTextScale, nil, nil, nil, nil, nil, true)) do
		updateTextScale = updateTextScale - 0.05
	end
	local downloadInProgress = true
	loadIndicator:addCustomDisplay(true, function()
			local downloads = get_downloads()
			if (#downloads == 0) then
				downloadInProgress = false
			end
			if (not downloadInProgress) then
				if (transparency[1] == 0.8) then
					viewElement:updateImage("../textures/clans/"..clanid..".tga", Clans.DefaultLogo, true)
				end
				transparency[1] = transparency[1] - 0.05
				if (transparency[1] <= 0) then
					table.insert(LOGOCACHE, clanid)
					loadView:kill()
				end
			end
			loadIndicator:uiText(TB_MENU_LOCALIZED.CLANSUPDATINGLOGO, nil, nil, nil, nil, updateTextScale, nil, nil, { 1, 1, 1, transparency[1] })
		end)
end
