-- network_request.lua
TB_NETWORK_REQUEST_QUEUE = TB_NETWORK_REQUEST_QUEUE or {}
TB_NETWORK_LASTREQUEST = TB_NETWORK_LASTREQUEST or nil

-- store_manager.lua
TB_INVENTORY_PAGE = TB_INVENTORY_PAGE or {}
TB_ITEM_DETAILS = TB_ITEM_DETAILS or nil
TB_INVENTORY_LOADED = TB_INVENTORY_LOADED or nil
INVENTORY_SELECTED_ITEMS = INVENTORY_SELECTED_ITEMS or {}

TB_INVENTORY_MODE = TB_INVENTORY_MODE or INVENTORY_DEACTIVATED
SHOW_EMPTY_SETS	= SHOW_EMPTY_SETS or 0

INVENTORY_UPDATE = false
INVENTORY_MOUSE_POS = { x = 0, y = 0 }

STORE_ICONS_DOWNLOAD_QUEUE = STORE_ICONS_DOWNLOAD_QUEUE or {}

-- player_info.lua
SERVER_USER_INFO = SERVER_USER_INFO or { updated = -1000 }

-- notifications_manager.lua
TB_MENU_NOTIFICATIONS_LASTSCREEN = TB_MENU_NOTIFICATIONS_LASTSCREEN or 3
TB_MENU_NOTIFICATIONS_LASTUPDATE = TB_MENU_NOTIFICATIONS_LASTUPDATE or { count = 0, data = 0 }
TB_MENU_NOTIFICATIONS_DATA = TB_MENU_NOTIFICATIONS_DATA or {}
TB_MENU_NOTIFICATIONS_NET_COUNT = TB_MENU_NOTIFICATIONS_NET_COUNT or 0
TB_MENU_NOTIFICATION_MESSAGE_LOADING = false

-- quests_manager.lua
QUESTS_UPDATE_CLOCK = QUESTS_UPDATE_CLOCK or nil
QUESTS_LASTUPDATE_GLOBAL = QUESTS_LASTUPDATE_GLOBAL or { time = 0, qi = 0 }
QUESTS_GLOBAL_DATA = QUESTS_GLOBAL_DATA or {}
TB_MENU_QUESTS_GLOBAL_COUNT = TB_MENU_QUESTS_GLOBAL_COUNT or 0
TB_MENU_QUESTS_COUNT = TB_MENU_QUESTS_COUNT or 0

-- clans_manager.lua
LOGOCACHE = LOGOCACHE or {}
AVATARCACHE = AVATARCACHE or {}

CLANLISTSHIFT = CLANLISTSHIFT or { 0 }
CLANSEARCHFILTERS = CLANSEARCHFILTERS or nil
CLANLISTLASTPOS = CLANLISTLASTPOS or { scroll = {}, list = {} }

-- replays_manager.lua
SERVER_REPLAYS = SERVER_REPLAYS or { action = 1, offset = 1, search = "", id = 0 }
SELECTED_FOLDER = SELECTED_FOLDER and { fullname = SELECTED_FOLDER.fullname } or { fullname = "replay" }
SELECTED_SERVER_REPLAY = SELECTED_SERVER_REPLAY or { id = 0 }
REPLAYS_CUSTOM_SELECTOR_ACTIVE = false

-- settings_manager.lua
dofile("system/settings_defines.lua")

-- ../tutorial/tutorial_manager.lua
TUTORIAL_STORED_OPTS = TUTORIAL_STORED_OPTS or {}

TUTORIALJOINTLOCK = false
TUTORIALKEYBOARDLOCK = false
TUTORIAL_SPECIAL_RP_IGNORE = false
