-- network_request.lua
---@type RequestData[]
TB_NETWORK_REQUEST_QUEUE = TB_NETWORK_REQUEST_QUEUE or {}
TB_NETWORK_LASTREQUEST = TB_NETWORK_LASTREQUEST or nil

-- store_manager.lua
ITEM_SET = 1458
ITEM_FLAME = 936
ITEM_SHIAI_TOKEN = 2528

INVENTORY_STARTUP = 0
INVENTORY_DEACTIVATED = 1
INVENTORY_ACTIVATED = 2
INVENTORY_ALL = 3

MODE_TC = 0
MODE_ST = 1

-- notifications_manager.lua
TB_MENU_NOTIFICATIONS_LASTSCREEN = TB_MENU_NOTIFICATIONS_LASTSCREEN or 2
TB_MENU_NOTIFICATIONS_UNREAD_COUNT = TB_MENU_NOTIFICATIONS_UNREAD_COUNT or 0

-- quests_manager.lua
QUESTS_LASTUPDATE = QUESTS_LASTUPDATE or { time = 0, qi = 0, requireUpdate = false }
TB_MENU_QUESTS_GLOBAL_COUNT = TB_MENU_QUESTS_GLOBAL_COUNT or 0
TB_MENU_QUESTS_COUNT = TB_MENU_QUESTS_COUNT or 0
TB_MENU_QUEST_NOTIFICATIONS = TB_MENU_QUEST_NOTIFICATIONS or 0
TB_MENU_QUESTS_ACTIVE_SECTION = TB_MENU_QUESTS_ACTIVE_SECTION or 1

QUESTS_DQ_ANY = 0
QUESTS_DQ = 1
QUESTS_POINTS = 2

-- clans_manager.lua
LOGOCACHE = LOGOCACHE or {}
AVATARCACHE = AVATARCACHE or {}

CLANLISTSHIFT = CLANLISTSHIFT or { 0 }
CLANLISTLASTPOS = CLANLISTLASTPOS or { scroll = {}, list = {} }

-- settings_manager.lua
dofile("system/settings_defines.lua")

TUTORIALJOINTLOCK = false
TUTORIALKEYBOARDLOCK = false
TUTORIAL_SPECIAL_RP_IGNORE = false

-- bounty_manager.lua
BOUNTIES_LAST_UPDATE = BOUNTIES_LAST_UPDATE or -1000
BOUNTY_ADD_ACTION = 110

-- market_manager.lua
MARKET_SELL = 300
MARKET_BUY = 301
MARKET_UPDATE = 302
MARKET_CANCEL = 303
MARKET_SAVESHOP = 304

-- battlepass_manager.lua
BATTLEPASS_SUBSCRIPTION_ITEM = 3613
BATTLEPASS_PURCHASE_LEVEL = 130
