-- network_request.lua
---@type RequestData[]
TB_NETWORK_REQUEST_QUEUE = TB_NETWORK_REQUEST_QUEUE or {}
TB_NETWORK_LASTREQUEST = TB_NETWORK_LASTREQUEST or nil

-- store_manager.lua
TB_INVENTORY_PAGE = TB_INVENTORY_PAGE or {}
TB_ITEM_DETAILS = TB_ITEM_DETAILS or nil
TB_INVENTORY_LOADED = TB_INVENTORY_LOADED or nil
INVENTORY_SELECTED_ITEMS = INVENTORY_SELECTED_ITEMS or {}

IGNORE_NAVBAR_SCROLL = 1000
TB_LAST_STORE_SECTION = TB_LAST_STORE_SECTION or 1

ITEM_SET = 1458
ITEM_FLAME = 936
ITEM_SHIAI_TOKEN = 2528

INVENTORY_STARTUP = 0
INVENTORY_DEACTIVATED = 1
INVENTORY_ACTIVATED = 2
INVENTORY_MARKET = 3
INVENTORY_ALL = 4

INVENTORY_DEACTIVATE = 1
INVENTORY_ACTIVATE = 2
INVENTORY_ADDSET = 3
INVENTORY_REMOVESET = 4
INVENTORY_UNPACK = 5
INVENTORY_UPGRADE = 6
INVENTORY_TEXTURERESET = 7
INVENTORY_EFFECTFUSE = 8
INVENTORY_EFFECTUPGRADE = 9
INVENTORY_EFFECTPURGE = 10

MODE_TC = 0
MODE_ST = 1

TB_INVENTORY_MODE = TB_INVENTORY_MODE or INVENTORY_STARTUP
SHOW_EMPTY_SETS	= SHOW_EMPTY_SETS or 0

INVENTORY_UPDATE = false
INVENTORY_MOUSE_POS = { x = 0, y = 0 }

STORE_ICONS_DOWNLOAD_QUEUE = STORE_ICONS_DOWNLOAD_QUEUE or {}

EFFECTS_NONE = 0
EFFECTS_TOON = 1
EFFECTS_GLOW = 2
EFFECTS_DITHER = 4

STORE_HAIR_CACHE = STORE_HAIR_CACHE or {}

-- player_info.lua
SERVER_USER_INFO = SERVER_USER_INFO or { updated = -1000 }

-- notifications_manager.lua
TB_MENU_NOTIFICATIONS_LASTSCREEN = TB_MENU_NOTIFICATIONS_LASTSCREEN or 2
TB_MENU_NOTIFICATIONS_LASTUPDATE = TB_MENU_NOTIFICATIONS_LASTUPDATE or { count = 0, data = 0 }
TB_MENU_NOTIFICATIONS_DATA = TB_MENU_NOTIFICATIONS_DATA or {}
TB_MENU_NOTIFICATIONS_NET_COUNT = TB_MENU_NOTIFICATIONS_NET_COUNT or 0
TB_MENU_NOTIFICATION_MESSAGE_LOADING = false

-- quests_manager.lua
QUESTS_LASTUPDATE = QUESTS_LASTUPDATE or { time = 0, qi = 0, requireUpdate = false }
TB_MENU_QUESTS_GLOBAL_COUNT = TB_MENU_QUESTS_GLOBAL_COUNT or 0
TB_MENU_QUESTS_COUNT = TB_MENU_QUESTS_COUNT or 0
TB_MENU_QUEST_NOTIFICATIONS = TB_MENU_QUEST_NOTIFICATIONS or 0
TB_MENU_QUESTS_ACTIVE_SECTION = TB_MENU_QUESTS_ACTIVE_SECTION or 1

QUESTS_DQ_ANY = 0
QUESTS_DQ = 1
QUESTS_POINTS = 2

-- clans_manager.lua
LOGOCACHE = LOGOCACHE or {}
AVATARCACHE = AVATARCACHE or {}

CLANLISTSHIFT = CLANLISTSHIFT or { 0 }
CLANSEARCHFILTERS = CLANSEARCHFILTERS or nil
CLANLISTLASTPOS = CLANLISTLASTPOS or { scroll = {}, list = {} }

-- replays_manager.lua
SERVER_REPLAYS = SERVER_REPLAYS or { action = 1, offset = 1, search = "", id = 0 }
SELECTED_FOLDER = SELECTED_FOLDER and { fullname = SELECTED_FOLDER.fullname } or { fullname = "replay" }
SELECTED_SERVER_REPLAY = SELECTED_SERVER_REPLAY or { id = 0 }
REPLAYS_CUSTOM_SELECTOR_ACTIVE = false
-- These have to be global to work correctly for replay save screen / events
REPLAY_TEMPNAME = "--onlinereplaytempfile"
REPLAY_SAVETEMPNAME = "--localreplaytempfile"
REPLAY_EVENT = "--eventtmp"

-- settings_manager.lua
dofile("system/settings_defines.lua")

-- ../tutorial/tutorial_manager.lua
TUTORIAL_STORED_OPTS = TUTORIAL_STORED_OPTS or {}

TUTORIALJOINTLOCK = false
TUTORIALKEYBOARDLOCK = false
TUTORIAL_SPECIAL_RP_IGNORE = false

-- bounty_manager.lua
BOUNTIES_LAST_UPDATE = BOUNTIES_LAST_UPDATE or -1000
BOUNTY_ADD_ACTION = 110

-- news_manager.lua
TB_MENU_NEWS_REFRESH = TB_MENU_NEWS_REFRESH or -10000

-- market_manager.lua
MARKET_SELL = 300
MARKET_BUY = 301
MARKET_UPDATE = 302
MARKET_CANCEL = 303
MARKET_SAVESHOP = 304

-- battlepass_manager.lua
BATTLEPASS_SUBSCRIPTION_ITEM = 3613
BATTLEPASS_PURCHASE_LEVEL = 130
