dofile("system/color_manager.lua")
dofile("toriui/uielement.lua")

ColorManager:create()
ColorManager:showMain()
add_hook("mouse_button_down", "uiMouseHandler", function(s, x, y) UIElement:handleMouseDn(s, x, y) end)
add_hook("mouse_button_up", "uiMouseHandler", function(s, x, y) UIElement:handleMouseUp(s, x, y) end)
add_hook("mouse_move", "uiMouseHandler", function(x, y) UIElement:handleMouseHover(x, y) end)
add_hook("draw2d", "colorManagerVisual", function() ColorManager:drawVisuals() end)
add_hook("draw3d", "colorManagerVisual", function() ColorManager:draw3dVisuals() end)